// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/uploader.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Shared.Protos {

  /// <summary>Holder for reflection information generated from Protos/uploader.proto</summary>
  public static partial class UploaderReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/uploader.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UploaderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVQcm90b3MvdXBsb2FkZXIucHJvdG8SD1VwbG9hZGVyUGFja2FnZSJRCglG",
            "aWxlQ2h1bmsSDAoEZGF0YRgBIAEoDBIOCgZvZmZzZXQYAiABKAMSEAoIaXNf",
            "ZmluYWwYAyABKAgSFAoMY2h1bmtfbnVtYmVyGAQgASgFIm0KDlVwbG9hZFBy",
            "b2dyZXNzEhYKDmJ5dGVzX3VwbG9hZGVkGAEgASgDEhMKC3RvdGFsX2J5dGVz",
            "GAIgASgDEhQKDHRvdGFsX2NodW5rcxgDIAEoBRIYChBjb21wbGV0ZWRfY2h1",
            "bmtzGAQgASgFMmAKD1VwbG9hZGVyU2VydmljZRJNCgpVcGxvYWRGaWxlEhou",
            "VXBsb2FkZXJQYWNrYWdlLkZpbGVDaHVuaxofLlVwbG9hZGVyUGFja2FnZS5V",
            "cGxvYWRQcm9ncmVzcygBMAFCEKoCDVNoYXJlZC5Qcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Protos.FileChunk), global::Shared.Protos.FileChunk.Parser, new[]{ "Data", "Offset", "IsFinal", "ChunkNumber" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Protos.UploadProgress), global::Shared.Protos.UploadProgress.Parser, new[]{ "BytesUploaded", "TotalBytes", "TotalChunks", "CompletedChunks" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FileChunk : pb::IMessage<FileChunk>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FileChunk> _parser = new pb::MessageParser<FileChunk>(() => new FileChunk());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FileChunk> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Protos.UploaderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FileChunk() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FileChunk(FileChunk other) : this() {
      data_ = other.data_;
      offset_ = other.offset_;
      isFinal_ = other.isFinal_;
      chunkNumber_ = other.chunkNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FileChunk Clone() {
      return new FileChunk(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "offset" field.</summary>
    public const int OffsetFieldNumber = 2;
    private long offset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Offset {
      get { return offset_; }
      set {
        offset_ = value;
      }
    }

    /// <summary>Field number for the "is_final" field.</summary>
    public const int IsFinalFieldNumber = 3;
    private bool isFinal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsFinal {
      get { return isFinal_; }
      set {
        isFinal_ = value;
      }
    }

    /// <summary>Field number for the "chunk_number" field.</summary>
    public const int ChunkNumberFieldNumber = 4;
    private int chunkNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChunkNumber {
      get { return chunkNumber_; }
      set {
        chunkNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FileChunk);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FileChunk other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      if (Offset != other.Offset) return false;
      if (IsFinal != other.IsFinal) return false;
      if (ChunkNumber != other.ChunkNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Offset != 0L) hash ^= Offset.GetHashCode();
      if (IsFinal != false) hash ^= IsFinal.GetHashCode();
      if (ChunkNumber != 0) hash ^= ChunkNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Data);
      }
      if (Offset != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Offset);
      }
      if (IsFinal != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsFinal);
      }
      if (ChunkNumber != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ChunkNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Data);
      }
      if (Offset != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Offset);
      }
      if (IsFinal != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsFinal);
      }
      if (ChunkNumber != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ChunkNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (Offset != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Offset);
      }
      if (IsFinal != false) {
        size += 1 + 1;
      }
      if (ChunkNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChunkNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FileChunk other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Offset != 0L) {
        Offset = other.Offset;
      }
      if (other.IsFinal != false) {
        IsFinal = other.IsFinal;
      }
      if (other.ChunkNumber != 0) {
        ChunkNumber = other.ChunkNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Data = input.ReadBytes();
            break;
          }
          case 16: {
            Offset = input.ReadInt64();
            break;
          }
          case 24: {
            IsFinal = input.ReadBool();
            break;
          }
          case 32: {
            ChunkNumber = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Data = input.ReadBytes();
            break;
          }
          case 16: {
            Offset = input.ReadInt64();
            break;
          }
          case 24: {
            IsFinal = input.ReadBool();
            break;
          }
          case 32: {
            ChunkNumber = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UploadProgress : pb::IMessage<UploadProgress>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UploadProgress> _parser = new pb::MessageParser<UploadProgress>(() => new UploadProgress());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UploadProgress> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Protos.UploaderReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UploadProgress() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UploadProgress(UploadProgress other) : this() {
      bytesUploaded_ = other.bytesUploaded_;
      totalBytes_ = other.totalBytes_;
      totalChunks_ = other.totalChunks_;
      completedChunks_ = other.completedChunks_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UploadProgress Clone() {
      return new UploadProgress(this);
    }

    /// <summary>Field number for the "bytes_uploaded" field.</summary>
    public const int BytesUploadedFieldNumber = 1;
    private long bytesUploaded_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BytesUploaded {
      get { return bytesUploaded_; }
      set {
        bytesUploaded_ = value;
      }
    }

    /// <summary>Field number for the "total_bytes" field.</summary>
    public const int TotalBytesFieldNumber = 2;
    private long totalBytes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalBytes {
      get { return totalBytes_; }
      set {
        totalBytes_ = value;
      }
    }

    /// <summary>Field number for the "total_chunks" field.</summary>
    public const int TotalChunksFieldNumber = 3;
    private int totalChunks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TotalChunks {
      get { return totalChunks_; }
      set {
        totalChunks_ = value;
      }
    }

    /// <summary>Field number for the "completed_chunks" field.</summary>
    public const int CompletedChunksFieldNumber = 4;
    private int completedChunks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CompletedChunks {
      get { return completedChunks_; }
      set {
        completedChunks_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UploadProgress);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UploadProgress other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BytesUploaded != other.BytesUploaded) return false;
      if (TotalBytes != other.TotalBytes) return false;
      if (TotalChunks != other.TotalChunks) return false;
      if (CompletedChunks != other.CompletedChunks) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BytesUploaded != 0L) hash ^= BytesUploaded.GetHashCode();
      if (TotalBytes != 0L) hash ^= TotalBytes.GetHashCode();
      if (TotalChunks != 0) hash ^= TotalChunks.GetHashCode();
      if (CompletedChunks != 0) hash ^= CompletedChunks.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BytesUploaded != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(BytesUploaded);
      }
      if (TotalBytes != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalBytes);
      }
      if (TotalChunks != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TotalChunks);
      }
      if (CompletedChunks != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CompletedChunks);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BytesUploaded != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(BytesUploaded);
      }
      if (TotalBytes != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalBytes);
      }
      if (TotalChunks != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TotalChunks);
      }
      if (CompletedChunks != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CompletedChunks);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BytesUploaded != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BytesUploaded);
      }
      if (TotalBytes != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalBytes);
      }
      if (TotalChunks != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalChunks);
      }
      if (CompletedChunks != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CompletedChunks);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UploadProgress other) {
      if (other == null) {
        return;
      }
      if (other.BytesUploaded != 0L) {
        BytesUploaded = other.BytesUploaded;
      }
      if (other.TotalBytes != 0L) {
        TotalBytes = other.TotalBytes;
      }
      if (other.TotalChunks != 0) {
        TotalChunks = other.TotalChunks;
      }
      if (other.CompletedChunks != 0) {
        CompletedChunks = other.CompletedChunks;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BytesUploaded = input.ReadInt64();
            break;
          }
          case 16: {
            TotalBytes = input.ReadInt64();
            break;
          }
          case 24: {
            TotalChunks = input.ReadInt32();
            break;
          }
          case 32: {
            CompletedChunks = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BytesUploaded = input.ReadInt64();
            break;
          }
          case 16: {
            TotalBytes = input.ReadInt64();
            break;
          }
          case 24: {
            TotalChunks = input.ReadInt32();
            break;
          }
          case 32: {
            CompletedChunks = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
